target("eg-mytest", function()
    set_kind("binary")
    add_deps("mytest")
    add_packages("spdlog", "boost", "cli11")
    add_includedirs("../tools/src/mytest/inc", { public = true })
    add_files("eg_mytest.cpp")
end)

target("eg-libs", function()
    set_kind("binary")
    add_deps("libs")
    add_packages("spdlog", "boost", "cli11")
    add_includedirs("../libs/inc", { public = true })
    add_files("eg_libs.cpp")
end)
