target("libs", function()
    set_kind("static")
    add_packages("spdlog", "boost", "cli11")
    add_includedirs("inc", { public = true })
    add_files("src/**.cpp")
    add_files("inc/**.hpp")
    add_files("../resources/**.ui")
    add_files("../resources/**.qrc")
    add_rules("qt.static")
    add_frameworks("QtNetwork", "QtGui", "QtCore", "QtWidgets", "QtMultimedia", "QtDBus")
end)
