target("mytest", function()
    set_kind("static")
    add_packages("spdlog", "boost", "cli11")
    add_includedirs("src/mytest/inc")
    add_headerfiles("src/mytest/inc/**.hpp")
    add_files("src/mytest/**.cpp")
    after_build(function(target)
        targetfile = target:targetfile()
        os.cp(targetfile, "./tools/lib/")
    end)
end)

target("rm", function()
    set_kind("binary")
    add_packages("spdlog", "cli11")
    add_includedirs("src/rm/inc")
    add_headerfiles("src/rm/inc/**.hpp")
    add_files("src/rm/src/**.cpp")
    after_build(function(target)
        targetfile = target:targetfile()
        os.cp(targetfile, "./tools/bin/")
    end)
end)

target("xxd", function()
    set_kind("binary")
    add_packages("spdlog", "cli11")
    add_includedirs("src/xxd/inc")
    add_headerfiles("src/xxd/inc/**.hpp")
    add_files("src/xxd/src/**.cpp")
end)
